import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Button from '@/components/button/button.componet';
import { BsFacebook, BsInstagram, BsTwitter, BsYoutube } from 'react-icons/bs';
import Footer from '@/components/footer/footer.component';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Footer />
      </main>
    </>
  );
}
